##docker stack deploy proxy --compose-file proxy.yml



version: "3"

services:

  haproxy:
    image: vfarcic/docker-flow-proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "8000:8000"
      - "8443:8443"
    environment:
      - LISTENER_ADDRESS=swarm-listener
	  - CFG_TEMPLATE_PATH
      - MODE=swarm
    volumes:
        - $PWD/data/dfp/haproxy.tmpl:/cfg/tmpl/haproxy.tmpl
        - my-haproxy:/usr/local/etc/haproxy/
    networks:
      - public
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - public
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://haproxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://haproxy:8080/v1/docker-flow-proxy/remove
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]		                                                   
      restart_policy:
        condition: on-failure
      
networks:
  public:
    driver: overlay
    ipam:
      driver: default
      config:
      - subnet: 10.1.0.0/24

volumes:	  
  my-haproxy:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $PWD/data/haproxy/	  
 
